# Generated by Django 4.2 on 2023-04-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de cliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='nombre cliente')),
                ('apellidoCliente', models.CharField(max_length=50, verbose_name='apellido cliente')),
                ('mailCliente', models.CharField(max_length=60, verbose_name='email cliente')),
                ('claveCliente', models.CharField(max_length=20, verbose_name='contraseña cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('identificador', models.CharField(max_length=255)),
                ('contador', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
            ],
        ),
    ]
