# Generated by Django 4.2 on 2023-04-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEntrega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('identificador', models.CharField(max_length=255)),
                ('contador', models.CharField(max_length=255)),
                ('cliente', models.CharField(max_length=255)),
            ],
        ),
    ]
