# Generated by Django 4.0.5 on 2023-05-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='guia_bodeguero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Guia',
        ),
    ]
