# Generated by Django 4.0.5 on 2023-05-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guia_bodeguero_delete_guia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guia_bodeguero',
        ),
        migrations.RemoveField(
            model_name='estadopedido',
            name='id_guia',
        ),
        migrations.DeleteModel(
            name='GuiaBodeguero',
        ),
    ]
