# Generated by Django 4.0.5 on 2023-05-06 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_boleta_estadopedido_detalleboleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaBodeguero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='estadopedido',
            old_name='vendedor',
            new_name='bodeguero',
        ),
        migrations.AddField(
            model_name='estadopedido',
            name='id_guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.guiabodeguero'),
        ),
    ]
