# Generated by Django 4.2 on 2023-05-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guiabodeguero_rename_vendedor_estadopedido_bodeguero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='pago',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
