# Generated by Django 4.0.5 on 2023-05-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopedido',
            name='estadoVendedor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
