# Generated by Django 4.0.5 on 2023-05-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_estadopedido_estadovendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopedido',
            name='vendedor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
