# Generated by Django 4.2 on 2023-05-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_estadopedido_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
