# Generated by Django 4.0.5 on 2023-05-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_id_boleta_detalleboleta_boleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
