# Generated by Django 4.2 on 2023-06-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_boleta_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='est_pago',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
