# Generated by Django 4.2 on 2023-05-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_boleta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalle',
            field=models.TextField(default='detalle'),
        ),
    ]
