# Generated by Django 4.0.5 on 2023-06-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_boleta_est_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
