# Generated by Django 4.2 on 2023-06-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitadoForms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, max_length=80, null=True)),
                ('direccion', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.boleta')),
            ],
        ),
    ]
