# Generated by Django 4.2 on 2023-06-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_invitadoforms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvitadoForms',
            new_name='Invitado',
        ),
    ]
