# Generated by Django 4.2 on 2023-07-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_categoria_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=60)),
                ('clave', models.CharField(max_length=20)),
            ],
        ),
    ]
